# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create(name: "Jay Pinho", email: "jay.pinho@moat.com", role: "normal")

Test.create(description: "Scroll down until X", expected_result: "Should do Y", test_link: "http://test.com")
Test.create(description: "Hover over X", expected_result: "Should expect Y", test_link: "http://test.com")
Test.create(description: 'Scroll video 100% into view; Let autoplay til 1s scroll out of view', expected_result: 'Should expect Y', test_link: 'http://test.com')
Test.create(description: 'Scroll video 100% into view; Let autoplay til 2s scroll out of view', expected_result: 'Should expect Y', test_link: 'http://test.com')
Test.create(description: 'Scroll video 100% into view; Let autoplay til 3s scroll out of view', expected_result: 'Should expect Y', test_link: 'http://test.com')
Test.create(description: 'Scroll video 100% into view; Let autoplay til 5s scroll out of view', expected_result: 'Should expect Y', test_link: 'http://test.com')
Test.create(description: 'Scroll video 100% into view; Let autoplay til 7s scroll out of view', expected_result: 'Should expect Y', test_link: 'http://test.com')
Test.create(description: 'Scroll video 100% into view; Let autoplay til 13s scroll out of view', expected_result: 'Should expect Y', test_link: 'http://test.com')
Test.create(description: 'Scroll video 100% into view; Let autoplay til 17s scroll out of view', expected_result: 'Should expect Y', test_link: 'http://test.com')
Test.create(description: 'Scroll video 100% into view; Let autoplay til completion scroll out of view', expected_result: 'Should expect Y', test_link: 'http://test.com')
Test.create(description: 'Scroll video 100% into view; click to fullscreen Let autoplay til 7s exit fullscreen scroll out of view', expected_result: 'Should expect Y', test_link: 'http://test.com')
Test.create(description: 'Scroll video 100% into view; click to fullscreen Let autoplay til 13s exit fullscreen scroll out of view', expected_result: 'Should expect Y', test_link: 'http://test.com')
Test.create(description: 'Scroll video 100% into view; click to fullscreen Let autoplay til 17s exit fullscreen scroll out of view', expected_result: 'Should expect Y', test_link: 'http://test.com')
Test.create(description: 'Scroll video 100% into view; click to fullscreen Let autoplay til completion exit fullscreen scroll out of view', expected_result: 'Should expect Y', test_link: 'http://test.com')
Test.create(description: 'Scroll video 100% into view; let video autoplay til 3s skip to 3s before end let video play til completion scroll out of view', expected_result: 'Should expect Y', test_link: 'http://test.com')
Test.create(description: 'Scroll video 100% into view click to enable fullscreen let video autoplay til 13s skip to last 2s of video watch til completion exit fullscreen scroll video out of view', expected_result: 'Should expect Y', test_link: 'http://test.com')
Test.create(description: 'Scroll video 100% into view click to enable fullscreen let video autoplay til 13s exit fullscreen scroll video out of view', expected_result: 'Should expect Y', test_link: 'http://test.com')
Test.create(description: 'Scroll video 80% into view enable sound with microphone let video autoplay til 13s scroll video out of view', expected_result: 'Should expect Y', test_link: 'http://test.com')
Test.create(description: 'Scroll video 100% in view let video autoplay til 18s scroll video out of view', expected_result: 'Should expect Y', test_link: 'http://test.com')
Test.create(description: 'Scroll video 100% into view; click retweet let video play to completion scroll out of view', expected_result: 'Should expect Y', test_link: 'http://test.com')
Test.create(description: 'Scroll video 100% into view; click to enable fullscreen click on retweet let video play to completion clcik to exit fullscreen scroll out of view', expected_result: 'Should expect Y', test_link: 'http://test.com')
Test.create(description: 'Scroll video 100% into view; let video autoplay til 6s click reply let video play to completion scroll out of view', expected_result: 'Should expect Y', test_link: 'http://test.com')
Test.create(description: 'Scroll video 100% into view; click to enable fullscreen let video autoplay til 7s click on reply let video play to completion clcik to exit fullscreen scroll out of view', expected_result: 'Should expect Y', test_link: 'http://test.com')
Test.create(description: 'Scroll video 100% into view; let video to autoplay til 6s click on send as message let video play to completion scroll out of view', expected_result: 'Should expect Y', test_link: 'http://test.com')
Test.create(description: 'Scroll video 100% into view; click to enable fullscreen click on send as message let video play to completion clcik to exit fullscreen scroll out of view', expected_result: 'Should expect Y', test_link: 'http://test.com')
Test.create(description: 'Scroll video 25% into view; let video play to completion scroll out of view', expected_result: 'Should expect Y', test_link: 'http://test.com')
Test.create(description: 'Scroll video 50% into view; let video play to completion scroll out of view', expected_result: 'Should expect Y', test_link: 'http://test.com')
Test.create(description: 'Scroll video 75% into view; let video play to completion scroll out of view', expected_result: 'Should expect Y', test_link: 'http://test.com')
Test.create(description: 'Scroll video 100% into view; let video begin to autoplay background the app within 1s let video play to completion scroll out of view', expected_result: 'Should expect Y', test_link: 'http://test.com')
Test.create(description: 'Scroll video 100% into view; click to enable fullscreen Let video autoplay til 9s background the app let video play to completion clcik to exit fullscreen scroll out of view', expected_result: 'Should expect Y', test_link: 'http://test.com')
Test.create(description: 'Scroll video 100% into view; let video play til 6s switch to another app let video play to completion return to twitter scroll out of view', expected_result: 'Should expect Y', test_link: 'http://test.com')
Test.create(description: 'Scroll video 100% into view; let video play to til 6s close app', expected_result: 'Should expect Y', test_link: 'http://test.com')
Test.create(description: 'Scroll video 100% into view; click to fullscreen let video play to til 6s close app', expected_result: 'Should expect Y', test_link: 'http://test.com')
Test.create(description: 'Scroll video 100% into view; let video autoplay til 6s click to fullscreen let video play til 15s close app', expected_result: 'Should expect Y', test_link: 'http://test.com')
Test.create(description: 'Scroll video 100% into view; let video autoplay til 6s click to fullscreen let video play til 20s close app', expected_result: 'Should expect Y', test_link: 'http://test.com')
Test.create(description: 'Scroll video 50% into view; let video play to til 3s scroll out of view', expected_result: 'Should expect Y', test_link: 'http://test.com')
Test.create(description: 'Scroll video 100% into view; allow video to autoplay enable airplane mode scroll video out of view scroll video back into view video should nt restart disable airplane mode scroll out and back into view let video play til 13s scroll out of view', expected_result: 'Should expect Y', test_link: 'http://test.com')
Test.create(description: 'Scroll video 100% into view; click to fullscreen let video autoplay til 6s enable airplane mode let vieo play til completion scroll out of view', expected_result: 'Should expect Y', test_link: 'http://test.com')
Test.create(description: 'Scroll video 100% into view; click to fullscreen swipe to pull down notification let video play til completion ensure that video pauses', expected_result: 'Should expect Y', test_link: 'http://test.com')
Test.create(description: 'Scroll video 100% into view; let video to autoplay swipe to pull down notification let video play til completion ensure that video pauses', expected_result: 'Should expect Y', test_link: 'http://test.com')
Test.create(description: 'Scroll video 100% into view; click to fullscreen let video autoplay til 7s lock the device let more then 30s pass unlock and scroll out of view', expected_result: 'Should expect Y', test_link: 'http://test.com')
Test.create(description: 'Scroll video 100% into view; let video autoplay <1s dashboard should be blank', expected_result: 'Should expect Y', test_link: 'http://test.com')
Test.create(description: 'Scroll video 100% into view; click to fullscreen let video autoplay <1s dashboard should be blank', expected_result: 'Should expect Y', test_link: 'http://test.com')
Test.create(description: 'Scroll video 100% into view; click on single view let video play til completion return back and scroll out of view', expected_result: 'Should expect Y', test_link: 'http://test.com')

Suite.create(name: "Facebook Display Phase 1")
Suite.create(name: "Facebook Video Phase 2")

Metric.create(name: "MRC Viewable", definition: "50% of pixels on-screen for 1 continuous second", metric_type: "display", ad_format: "All", environment: "All", test_slots_count: 2, suite_id: 1)
Metric.create(name: "GroupM Viewable Display", definition: "100% of pixels on-screen with no time minimum", metric_type: "display", ad_format: "All", environment: "All", test_slots_count: 2, suite_id: 1)
Metric.create(name: "GroupM Viewable Video", definition: "100% of pixels on-screen and audible for half the duration, capped at 15 seconds", metric_type: "video", ad_format: "All", environment: "All", test_slots_count: 3, suite_id: 2)

Assignment.create(metric_id: 1, test_id: 1, test_slot: 1)
Assignment.create(metric_id: 1, test_id: 2, test_slot: 2)
Assignment.create(metric_id: 2, test_id: 1, test_slot: 2)
Assignment.create(metric_id: 2, test_id: 2, test_slot: 1)

Result.create(test_id: 2, passed: true, user_id: 1, completed_at: '2017-02-01 00:00:00')
Result.create(test_id: 1, passed: false, note: "Not sure what happened", user_id: 1, completed_at: '2017-02-01 00:00:00')
Result.create(test_id: 2, note: "Still not sure what happened", user_id: 1)
